version: "3.3"
  
services:
  yifanserver:
    image: gary80221/yifanserver
    ports:
      - "5000"  
    environment:
      CONNECTSTRING: ${CONNECTSTRING}
      LINEBOT_POST_TOKEN: ${LINEBOT_POST_TOKEN}
      LINEBOT_RECV_TOKEN: ${LINEBOT_RECV_TOKEN}     
 
 