version: "3.3"
  
services:
  yifanserver:
    image: gary80221/yifanserver
    ports:
      - "5000:5000"  
    build: .
    environment:
      CONNECTSTRING: ${CONNECTSTRING}
      LINEBOT_POST_TOKEN: ${LINEBOT_POST_TOKEN}
      LINEBOT_RECV_TOKEN: ${LINEBOT_RECV_TOKEN}   
      YIFANSERV_SERVER_PORT: ${YIFANSERV_SERVER_PORT}  
      SSL_PEM : /run/secrets/SSL_PEM
      SSL_KEY : /run/secrets/SSL_KEY      
    secrets:
      - SSL_PEM
      - SSL_KEY

secrets:
  SSL_PEM:
    file: ./SSL_YiFanServer/yfnoip_ddns_net.pem-chain
  SSL_KEY: 
    file: ./SSL_YiFanServer/YiFanServer.Key      
 
 