version: "3.3"
secrets:
  LINEBOT_POST_TOKEN_secret:
    external: true
  LINEBOT_RECV_TOKEN_secret:
    external: true
  CONNECTSTRING_secret:
    external: true        
    
services:
  yifanserver:
    image: gary80221/yifanserver
    ports:
      - "5000"  

    secrets:
      - LINEBOT_POST_TOKEN_secret
      - LINEBOT_RECV_TOKEN_secret
      - CONNECTSTRING_secret

    environment:
      - LINEBOT_POST_TOKEN: /run/secrets/LINEBOT_POST_TOKEN_secret
      - LINEBOT_RECV_TOKEN: /run/secrets/LINEBOT_RECV_TOKEN_secret
      - CONNECTSTRING: /run/secrets/CONNECTSTRING_secret
 